# Site settings
name: Less Or More
email: 309712560@qq.com
author: Lin Tao
url: http://www.lintao.online
resume_site: http://www.lintao.online/cv.html
github: https://github.com/lintaoonline/
baseurl: ""
description: Actually, I'm not a Kobe fan!
meta_description: 林韬;个人博客
motto: Never underestimate the heart of a champion.
banner: when i was young. they call me "小科比" ;

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lintaoonline
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : lintaoonline
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
